"use strict";
export let checklist = [
  {
    completed: false,
    item: "OXYGEN",
    value: "TESTED, 100%",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "INST XFER AND DISPLAY SWITCHES",
    value: "NORMAL, AUTO",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "WINDOW HEAT",
    value: "ON",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "PRESSURIZATION MODE SELECTOR",
    value: "AUTO",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "PARKING BRAKE",
    value: "SET",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "ENGINE START LEVERS",
    value: "CUTOFF",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "FLIGHT INSTRUMENTS",
    value: "SET",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "IFR CLEARANCE",
    value: "RECIEVED",
    slc: true,
    stage: "preflight",
  },
  {
    completed: false,
    item: "FLIGHT DECK DOOR",
    value: "CLOSED AND LOCKED",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "FUEL",
    value: "____ KGS/LBS, PUMPS ON",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "PASSENGER SIGNS",
    value: "ON AFTER REFULING",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "WINDOWS",
    value: "LOCKED",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "MCP",
    value: "SET",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "TAKEOFF SPEEDS",
    value: "SET",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "CDU PREFLIGHT",
    value: "COMPLETED",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "RUDDER AND AILERON TRIM",
    value: "FREE AND ZERO",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "TAXI AND TAKEOFF BRIEFING",
    value: "COMPLETED",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "APU",
    value: "STARTED, GROUND CREW INFORMED",
    slc: true,
    stage: "before-start",
  },
  {
    completed: false,
    item: "GPU",
    value: "REMOVED, GROUND CREW INFORMED",
    slc: true,
    stage: "before-start",
  },
  {
    completed: false,
    item: "WELCOME ABOARD PA",
    value: "GIVEN, ALL PASSENGERS ABOARD",
    slc: true,
    stage: "before-start",
  },
  {
    completed: false,
    item: "ANTI COLLITION LIGHTS",
    value: "ON",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "PREPARE FOR PUSHBACK",
    value: "GSX/SLC",
    slc: true,
    stage: "before-start",
  },
  {
    completed: false,
    item: "PUSH AND START REQUEST",
    value: "APPROVED",
    slc: true,
    stage: "before-start",
  },
  {
    completed: false,
    item: "ENGINES",
    value: "STARTED, GROUND CREW INFORMED",
    slc: true,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "GENERATORS",
    value: "ON",
    slc: false,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "PROBE HEAT",
    value: "ON",
    slc: false,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "ANTI ICE",
    value: "____",
    slc: false,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "ISOLATION VALVED",
    value: "AUTO",
    slc: false,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "ENGINE START SWITCHES",
    value: "CONTINUOUS",
    slc: false,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "RECALL",
    value: "CHECKED",
    slc: false,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "AUTOBRAKE",
    value: "RTO",
    slc: false,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "ENGINE START LEVERS",
    value: "IDLE DETENT",
    slc: false,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "FLIGHT CONTROLS",
    value: "CHECKED",
    slc: false,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "GROUND EQUIPMENT",
    value: "CLEAR",
    slc: false,
    stage: "before-taxi",
  },
  {
    completed: false,
    item: "FLAPS",
    value: "____, GREEN LIGHT",
    slc: false,
    stage: "before-takeoff",
  },
  {
    completed: false,
    item: "STABILIZER TRIM",
    value: "____ UNITS",
    slc: false,
    stage: "before-takeoff",
  },
  {
    completed: false,
    item: "SEATS FOR TAKEOFF PA",
    value: "COMPLETED",
    slc: true,
    stage: "before-takeoff",
  },
  {
    completed: false,
    item: "LANDING LIGHTS",
    value: "ON",
    slc: true,
    stage: "before-takeoff",
  },
  {
    completed: false,
    item: "STROBES",
    value: "ON",
    slc: true,
    stage: "before-takeoff",
  },
  {
    completed: false,
    item: "TRANSPONDER",
    value: "TA/RA",
    slc: true,
    stage: "before-takeoff",
  },
  {
    completed: false,
    item: "ENGINE BLEEDS",
    value: "ON",
    slc: false,
    stage: "after-takeoff",
  },
  {
    completed: false,
    item: "PACKS",
    value: "AUTO",
    slc: false,
    stage: "after-takeoff",
  },
  {
    completed: false,
    item: "LANDING GEAR",
    value: "UP AND OFF",
    slc: false,
    stage: "after-takeoff",
  },
  {
    completed: false,
    item: "FLAPS",
    value: "UP, NO LIGHTS",
    slc: false,
    stage: "after-takeoff",
  },
  {
    completed: false,
    item: "CABIN CREW",
    value: "RELEASED",
    slc: true,
    stage: "after-takeoff",
  },
  {
    completed: false,
    item: "ALTIMITERS",
    value: "SET AND CROSS CHECKED",
    slc: false,
    stage: "cruise",
  },
  {
    completed: false,
    item: "FUEL",
    value: "CHECKED, BALANCED",
    slc: false,
    stage: "cruise",
  },
  {
    completed: false,
    item: "INTERCOM DECENT INFO",
    value: "GIVEN, 20-30 MINS BEFORE TOD",
    slc: true,
    stage: "cruise",
  },
  {
    completed: false,
    item: "PA DECENT INFO",
    value: "GIVEN, 20-30 MINS BEFORE TOD",
    slc: true,
    stage: "cruise",
  },
  {
    completed: false,
    item: "PA DECENT STARTED",
    value: "GIVEN",
    slc: true,
    stage: "descent",
  },
  {
    completed: false,
    item: "PRESSURIZATION",
    value: "LANDING ALT____",
    slc: false,
    stage: "descent",
  },
  {
    completed: false,
    item: "RECALL",
    value: "CHECKED",
    slc: false,
    stage: "descent",
  },
  {
    completed: false,
    item: "AUTOBRAKE",
    value: "____",
    slc: false,
    stage: "descent",
  },
  {
    completed: false,
    item: "LANDING DATA",
    value: "VREF____ MINIMUMS____",
    slc: false,
    stage: "descent",
  },
  {
    completed: false,
    item: "APPROACH BRIEFING",
    value: "COMPLETED",
    slc: false,
    stage: "descent",
  },
  {
    completed: false,
    item: "PASSENGER SIGNS",
    value: "ON",
    slc: true,
    stage: "descent",
  },
  {
    completed: false,
    item: "PREPARE CABIN FOR LANDING PA",
    value: "GIVEN",
    slc: true,
    stage: "descent",
  },
  {
    completed: false,
    item: "ALTIMITERS",
    value: "____ SET",
    slc: false,
    stage: "approach",
  },
  {
    completed: false,
    item: "ALTIMITERS",
    value: "____ SET",
    slc: false,
    stage: "approach",
  },
  {
    completed: false,
    item: "SEATS FOR LANDING PA",
    value: "GIVEN",
    slc: true,
    stage: "approach",
  },
  {
    completed: false,
    item: "ENGINE START SWITCHES",
    value: "CONT",
    slc: false,
    stage: "landing",
  },
  {
    completed: false,
    item: "SPEED BRAKE",
    value: "ARMED",
    slc: false,
    stage: "landing",
  },
  {
    completed: false,
    item: "LANDING GEAR",
    value: "DOWN",
    slc: false,
    stage: "landing",
  },
  {
    completed: false,
    item: "FLAPS",
    value: "____, GREEN LIGHT",
    slc: false,
    stage: "landing",
  },
  {
    completed: false,
    item: "FLAPS",
    value: "UP, NO LIGHT",
    slc: false,
    stage: "after-landing",
  },
  {
    completed: false,
    item: "SPEED BRAKES",
    value: "UP",
    slc: false,
    stage: "after-landing",
  },
  {
    completed: false,
    item: "APU",
    value: "STARTED",
    slc: false,
    stage: "after-landing",
  },
  {
    completed: false,
    item: "DISARM DOORS PA",
    value: "GIVEN",
    slc: true,
    stage: "after-landing",
  },
  {
    completed: false,
    item: "PARKING BRAKES",
    value: "SET",
    slc: false,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "ENGINE START LEVERS",
    value: "CUTOFF",
    slc: false,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "ANTI COLLISION LIGHTS",
    value: "OFF",
    slc: true,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "GPU",
    value: "CONNECTED AND ON",
    slc: true,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "APU",
    value: "OFF",
    slc: false,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "WEATHER RADAR",
    value: "OFF",
    slc: false,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "FUEL PUMPS",
    value: "OFF",
    slc: false,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "PROBE HEAT",
    value: "OFF",
    slc: false,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "HYDRAULICS PANEL",
    value: "SET",
    slc: false,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "PASSENGER SIGNS",
    value: "OFF",
    slc: true,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "DEBOARDING",
    value: "REQUESTED",
    slc: true,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "DEBOARDING PA",
    value: "GIVEN",
    slc: true,
    stage: "shutdown",
  },
  {
    completed: false,
    item: "IRS's",
    value: "OFF",
    slc: false,
    stage: "securing-aircraft",
  },
  {
    completed: false,
    item: "EMERGENT EXIT LIGHTS",
    value: "OFF",
    slc: false,
    stage: "securing-aircraft",
  },
  {
    completed: false,
    item: "WINDOW HEAT",
    value: "OFF",
    slc: false,
    stage: "securing-aircraft",
  },
  {
    completed: false,
    item: "PACKS",
    value: "OFF",
    slc: false,
    stage: "securing-aircraft",
  },
];
