let checks = [
  {
    completed: false,
    item: "OXYGEN",
    value: "TESTED, 100%",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "INST XFER & DISPLAY SWITCHES",
    value: "NORMAL, AUTO",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "WINDOW HEAT",
    value: "TESTED, ON",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "PRESSURIZATION MODE SELECTOR",
    value: "AUTO",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "FLIGHT INSTRUMENTS",
    value: "SET",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "PARKING BRAKE",
    value: "SET",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "ENGINE START LEVERS",
    value: "CUTOFF",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "IFR CLEARANCE",
    value: "RECIEVED",
    slc: false,
    stage: "preflight",
  },
  {
    completed: false,
    item: "FLIGHT DECK DOOR",
    value: "CLOSED & LOCKED",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "FUEL",
    value: "____ KGS/LBS, PUMPS ON",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "PASSENGER SIGNS",
    value: "ON AFTER REFULING",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "WINDOWS",
    value: "LOCKED",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "MCP",
    value: "SET",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "TAKEOFF SPEEDS",
    value: "SET",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "CDU PREFLIGHT",
    value: "COMPLETED",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "RUDDER AND AILERON TRIM",
    value: "FREE & ZERO",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "TAXI & TAKEOFF BRIEFING",
    value: "COMPLETED",
    slc: false,
    stage: "before-start",
  },
  {
    completed: false,
    item: "ANTI COLLITION LIGHTS",
    value: "ON",
    slc: false,
    stage: "before-start",
  },
];
